#!/bin/sh
#
# chkconfig:   - 99 01
# description: This scripts turns blackbird on/off
# processname: blackbird
# config:      /etc/blackbird/defaults.cfg
#

. /etc/rc.d/init.d/functions

RETVAL=0

start() {
    echo -n $"Stating blackbird: "
    /usr/bin/blackbird -c /etc/blackbird/defaults.cfg
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
        success
        touch /var/lock/subsys/blackbird
    else
        failure
    fi
    echo
}

stop() {
    echo -n $"Stopping blackbird: "
    killproc -p /var/run/blackbird/blackbird.pid
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
        success
        rm -f /var/lock/subsys/blackbird
    else
        failure
    fi
    echo
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac

exit $RETVAL
